# Generated by Django 5.2.5 on 2026-07-19 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_userrole"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["module"], name="permissions_module_2c0512_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["action"], name="permissions_action_208379_idx"),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["code"], name="permissions_code_a0a529_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["name"], name="roles_name_a96913_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["code"], name="roles_code_25c050_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["is_active"], name="roles_is_acti_723ee4_idx"),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(fields=["role"], name="role_permis_role_id_0ea48f_idx"),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["permission"], name="role_permis_permiss_96a6c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["user"], name="user_roles_user_id_05df60_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="user_roles_role_id_0b583b_idx"),
        ),
    ]
